### ISSUE TITLE
Support speaker notes

### ISSUE THREAD

**Issue by wyozi** [wyozi/react-pptx#111]
https://gitbrent.github.io/PptxGenJS/docs/speaker-notes.html

Steps:
- Add new properties to the `<Slide>` component
- Add new normalized properties for `InternalSlide`
- Implement adding notes in renderer
- (Optionally) Implement basic speaker notes display in preview component

**Comment by ksk385** [comment]
Any update if this is being worked on?

**Comment by wyozi** [comment]
@ksk385 not actively but it's quite an easy feature to add yourself, if you're interested! I can give some more guidance if needed

**Comment by wyozi** [comment]
@Mubashir1044 great! Let me know if there's anything unclear in the process

**Comment by ksk385** [comment]
@wyozi please let me know if this works: https://github.com/wyozi/react-pptx/pull/639

Also, I would like to understand the best way to test this change. Can I run the demo locally?

**Comment by ksk385** [comment]
Thanks for merging @wyozi !

What is the typical release cadence? I am guessing you will close this issue it gets packed and released?

**Comment by wyozi** [comment]
@ksk385 should get automatically released once the PR is merged (although had to fix a small lint issue and create a commit with specific message to trigger the release). The release process uses semantic release commit format (https://github.com/semantic-release/semantic-release#commit-message-format), so adding those to commit messages helps a bit with the release process :)

**Comment by wyozi** [comment]
Implemented in #639
