### ISSUE TITLE
Full Integration Example of use

### ISSUE THREAD

**Issue by rayonnunes** [wyozi/react-pptx#136]
Hi, can I ask you for a more complete example of how to properly use your package?

I'm new to React and I'm having problems to run the basic example.

I get the following error:
`Unhandled Rejection (TypeError): fs.writeFile is not a function`

If you could share a full example or a Codesandbox/JSFiddle example I would really appreciate

**Comment by wyozi** [comment]
`fs.writeFile` is just for Node environment. You can see a full browser example inside https://github.com/wyozi/react-pptx/tree/master/pages
