### ISSUE TITLE
support for defineLayout

### ISSUE THREAD

**Issue by cpappala-godaddy** [wyozi/react-pptx#663]
Thanks for creating this awesome package!!!
I see `PptxGenJS` supports to add custom layout size which is missing in the react version.
https://gitbrent.github.io/PptxGenJS/docs/usage-pres-options/#custom-slide-layouts

**Comment by wyozi** [comment]
Thanks for the feature request. Would you be interested in implementing this as a PR?

**Comment by ChaitanyaKrishnaPappala** [comment]
> Thanks for the feature request. Would you be interested in implementing this as a PR?

Yes please, this is my personal github account, please let me know the process to raise a PR.

**Comment by wyozi** [comment]
Fixed in https://github.com/wyozi/react-pptx/pull/664
