### ISSUE TITLE
Not render

### ISSUE THREAD

**Issue by Diagru25** [wyozi/react-pptx#668]
I copy example on site
<img width="435" alt="image" src="https://user-images.githubusercontent.com/31183495/211141750-c6a966fd-049d-415f-af91-678df9272a8c.png">
but I got an error:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/31183495/211141814-7d480a25-1ab0-4e73-b66f-3e9d8166d997.png">
How can I fix it?
Thanks

**Comment by wyozi** [comment]
You need to wrap it in a <Preview/> node to preview it on a website, e.g.

```tsx
import Preview from "react-pptx/preview";

// and then in App
<Preview
  slideStyle={{ border: "1px solid black" }}
>
  <Presentation>
  </Presentation>
</Preview>
```
