### ISSUE TITLE
background image for <Slide/> 

### ISSUE THREAD

**Issue by s-kris** [wyozi/react-pptx#73]
Can you support for background image for slide?
https://github.com/gitbrent/PptxGenJS/issues/778#issuecomment-648537664

Thanks for this lib!

**Comment by wyozi** [comment]
Sure, looks like pptxgenjs 3.3.0 (which will have the feature) isn't publicly released yet though. I'll try to stick up to date with the released non-beta npm version.

**Comment by wyozi** [comment]
Fixed in latest version
