### ISSUE TITLE
Accept data URIs for images

### ISSUE THREAD

**Issue by wyozi** [wyozi/react-pptx#76]
Namely for `slide.background` and `image`. They're both `OptsDataOrPath` so we can have a single function accepting `pathOrData` and map it to either one based on existence of the base64 prefix.

Implementation steps:
- In renderer, check if image layer's url has the base64 prefix
- If it has the prefix, we can just use the url as is (no need to fetch anything)

**Comment by mckdanoventa** [comment]
URL is currently a required field. If I wanted to use `data` for the field instead of `url` in order to pass the `${contentType};base64,${data}` would you see this as a valid option? I'd like to pick this issue up if you're not actively working on it.

**Comment by wyozi** [comment]
Fixed in #180 with great work by @mckdanoventa :)
