### ISSUE TITLE
Support for complex color object

### ISSUE THREAD

**Issue by CroniD** [wyozi/react-pptx#8]
Hi there,

this project is really cool. :)

But... it doesn't support complex color objects, e.g.
```javascript
{
	type: 'solid',
	color: '000000',
	alpha: 0
}
```
There are a couple of types possible, also a color taken from a context in react might be of any form (#000, #00, #000000, rgb(0,0,0) etc.). If you promote this kind of styling, then you need to make sure it works or provide coverters. Alpha values ranges from 0 to 100. There might be other props.

Complex color objects are relevant for properties like color, fill, line etc. and can be applied to most addXyz function, even if not documentated. There are a lot of "hidden" properties and possiblities for pptxgenjs actually.

I hope this helps and I'm looking forward how this project progress. :)

Best regards

**Comment by wyozi** [comment]
Thanks, for sure this is helpful information! I think going with CSS colors (with e.g. something like d3-color) would make the most sense.
